default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  port: 5432
  host: ''
  database: events
  username: kacper
  password:

test:
  <<: *default
  database: events_test

production:
  <<: *default
  database: events_production
  username: events
  password: 
